#!/bin/bash

# task1

tab1=(el1 el2 el3 el4 el5)

for i in {0..4}; do
  echo $((i+1)): ${tab1[i]}
done

# task2

echo -e "1+4\n5+6\n6+2" > data

sum=0
for k in $(cat data); do
	echo $k = $((k))
	((sum+=$k))
done
echo suma = $sum
